In [26]:
import numpy as np

In [27]:
# where to see the version you are running on numpy

print(np.__version__)

1.20.1


In [28]:
# 3. Create a null vector of size 10 (★☆☆)

zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
# 4. How to find the memory size of any array (★☆☆)

print(zeros.size)
print(zeros.itemsize)
size_bytes = zeros.size * zeros.itemsize
print("The total size of the zeros array is {zeros.size * zeros.itemsize} bytes")

10
8
The total size of the zeros array is {zeros.size * zeros.itemsize} bytes


In [15]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [18]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆

# Creating a hard copy
zeros_b = zeros.copy()
print(zeros_b)
zeros_b[4]=1
print(zeros_b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)

vector_1=np.arange(10,50,1)
print(vector_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
# 8. Reverse a vector (first element becomes last) (★☆☆)

# these columns are separating the start and end point and how large are the steps inbetween
# 1 value -> just select one value, 2 values neaning a range, and 3 values meaning a range with a step
# -> as we have in the example
reverse_vector_1=vector_1[: : -1]
print(reverse_vector_1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
